### ISSUE TITLE
Tauren: Tauren age is wrong, and height is a bit short

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#167]
The tauren race are a bit below the average of what it should be. 
https://wow.gamepedia.com/Life_spans

Some people have also commented that the tauren's height is a bit short by how the race is written. It's a question whether we should make the race be "Large" though; no playable races are. 

Main reason why no playable races are Large, is that it would massively affect how they'd wield weapons and how they'd navigate spaces compared to even Medium creatures. 
https://rpg.stackexchange.com/questions/69967/are-there-any-rules-or-guidelines-for-large-character-races

But, this is what the Powerful Build feature and similar things are for. Let a race count as being Large, and let it have the documented height as being larger than the average human (6 feet tall, versus the 9-10 feet tall tauren) without that directly making them a Large race.

**Comment by Jihia** [comment]
Changed their old age from 80 to 95.
A second pass of races will be adjusting each races height so that it corresponds with Warcraft lore.
