### ISSUE TITLE
Goblin: Swap +1 Int for +1 Dex

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#168]
Right now, the goblin ASI needs a bit of a change to make them have a broader appeal.

The Gnome ASI is +2 Int and +1 Cha. The Goblin ASI is +1 int and +2 Cha. 

If the Goblin ASI was changed to +1 Dex and +2 Cha, they'd be more open for other character options. Though we should also consider how many other races in the Horde have a +1 Int vs a +1 Dex.

**Comment by Jihia** [comment]
There is also an error at the beginning of Goblin Traits as the introduction text before their race traits reads "Your gnome character has certain abilities, learned through generations of gnomes."

**Comment by Jihia** [comment]
Changed their ASI to +1 Dex/+2 Cha, instead of +1 Int/+2 Cha
