### ISSUE TITLE
Warrior: Add a Cleave attack

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#171]
Being able to Cleave targets is a big staple of the warrior class -- nowadays mainly for the Arms warrior, but historically for the warrior as a whole (available for all before Warlords of Draenor). 

- How would it be be used? 

- How much would it cost to do?

**Comment by Jihia** [comment]
Maybe draw some inspiration from the Battle Master's Maneuver _Sweeping Attack_? It would go something like this:

"When you hit a creature with a melee weapon attack, you can expend _X_ rage attempt to damage another creature with the same attack. Choose another creature within 5 feet of the original target and within your reach. If the original attack roll would hit the second creature, it takes damage equal to half your warrior level. The damage is of the same type dealt by the original attack."

Additional damage to the secondary target is a bi-product of it normally using superiority dies and could potentially be removed entirely if the rage cost is low enough?
