### ISSUE TITLE
Book: Update world maps at the end of the book with Chronicles 3

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#180]
Chronicles 3 added new maps of Azeroth, both before and after the Sundering.

We could update the single map of the current post-sundering Azeroth with two of these new maps.

[In the Wake of the Third War](https://gamepedia.cursecdn.com/wowpedia/4/44/Chron3_map_of_Azeroth_at_AQ_reopening.jpg?version=9706e5aca9b125b473599477f63ac443)

[The Shattering of Azeroth](https://gamepedia.cursecdn.com/wowpedia/4/4e/Chron3_map_of_Azeroth_after_the_Cataclysm.jpg?version=ed5cd04011c8d8021161eb6ed5c69771)

**Comment by Jihia** [comment]
World Map has been updated.
