### ISSUE TITLE
Mage: Study of Arcane Potent Cantrip feature

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#234]
- Study of Arcane's 6th level feature is near useless as there's only two mage cantrips that requires a saving throw.
- Maybe replace it with School of War Magic's *Arcane Deflection*?

**Comment by orjanbp** [comment]
One thing that might be a good option, is to work in a _Rule of Threes_ feature.

Out of a conversation with Atmosphere and OreoGolem in the feedback forum, it'd essentially be as follows. 

- Once per turn when casting a levelled spell, the mage gains 1 Arcane Charge.

- At 3 charges, the mage expend a spell slot to cast _Magic Missiles_ as a reaction. This can happen on the same turn as the last charge was gained.

- The _Magic Missiles_ spell slot doesn't generate a charge.

- While the mage has 3 charges, no additional charges are generated.

**Comment by Jihia** [comment]
Auvreannia has pointed out that the damage ramps of the *rule of three* does not correspond with the min-max an arcane missile spell cast at that level. (?)

**Comment by Jihia** [comment]
Another potential 6th feature for Arcane.

### Prodigious Memory
Starting at 6th level, you have attained a greater mastery of spell preparation. While on short rest, you can replace amount of spells equal to half of your Mage level (rounded down) that you have prepared with another spells from your spellbook.
