### ISSUE TITLE
Tauren: Do Mulgore Taurens overlap too much with elemental shamans?

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#253]
Mulgore Tauren were commented as having a bit of an overlap with elemental shamans.

On a closer look, the only real overlap seems to be that the Mulgore Tauren *War Stomp* feature is a once per long rest case of *Earth Tremor*, which also features on the Elemental Shaman list of binding spells.

We could arguably change up the elemental binding spell list, but this isn't necessarily a huge problem. It's only one spell with a free extra cast per day.

**Comment by Jihia** [comment]
A minuscule overlap, nothing that's worth making real changes for.
