### ISSUE TITLE
Warlock: Reworking demon pets, and add a Felguard option

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#299]
We should take another look through the demon pets available to Warlocks, at the moment there's some inconsistency between the different monsters that we should get rid of to make sure one isn't inherently better than the others, but that they are of equal strength for different situations.

Someone mentioned that there's currently no Felguard demon pet available to Warlocks either, something we should look into fixing so that they have a big slow heavy hitter if desired.

**Comment by Tyloris** [comment]
Demons were reworked with the new warlock class. Felguard was added as an option.
