### ISSUE TITLE
Tauren: Should tauren's be Large sized creatures?

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#316]
The Tauren race as a whole is a bit shorter than what the average tauren should be, this was done to keep them as a Medium sized creature without breaking the mold. 
But should they be a Medium sized creature? we could try and work them into being a "fake" Large sized creature, only granting them certain benefits from their size.

Potentially go something like this
"Because of your large size, you take up a 10 by 10 foot area. You still have a 5-foot reach. You are able to grapple huge creatures. When you wield a versatile weapon in one hand you deal damage with it as if you were wielding it with both hands. If you use small weapons you do so with disadvantage."

**Comment by orjanbp** [comment]
Connected to #167 

Wizards attempted to balance out Large-esque player races in some D&D 5e supplements with the "Powerful Build" feature, which taurens already do have. 

If the size is already specified as being Medium and there's no confusion to think the creature does actually count as Large, then we at least avoid the worst parts of the affair. I.e.

- The tauren wouldn't be able to wield oversized weapons (1 extra damage die on the weapon).

- The tauren wouldn't be able to be enlarged to a Huge creature. 

But problems arise if we try and push the tauren to a bigger 10x10 base. 

- Squeezing rules change pretty drastically. 

- It could be misinterpreted as the creature actually being Large even if that's not supposed to be the case.

Beyond that, the ability to grapple a Huge creature would follow implications that the tauren would be able to grapple even bigger creatures if enlarged. That's probably not something we really want to see.

**Comment by Jihia** [comment]
Player character's should not be Large sized, this has since been discussed and agreed upon.
