### ISSUE TITLE
Warlock: Life tap should be able to kill the Warlock

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#345]
We should add a line to Life Tap that says that if they are reduced to 0 hit point they die, similar to how monsters life drain kill a creature if they reduce their maximum HP to 0.

**Comment by orjanbp** [comment]
The rewrites for the 3.0 Life Tap all build around the hit dice instead of the warlock's hit points, so this issue might be deprecated.
