### ISSUE TITLE
Warlock: Should we bring back Invocations?

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#371]
Our Warlock is heavily based on the 5e Warlock, with only a few design choices deviating from the structure of the 5e Warlock. The biggest of which is our choice to not have any Invocations and instead focus our warlock more on their new _Life Tap_ ability and more powerful _Shadow Embraces_.

In the past we've talked about reworking the Warlock more and implementing Invocations once more. A way we could make the invocations play an even bigger role is rework the Shadow Embraces and make a pet base-line for all Warlocks, adding in a _Grimoire of Sacrifice_ option for those who do not want a companion, simply empowering themselves further. 

With a base-line pet we could add more unique invocations and deviate from 5e by having some affect both the Warlock and their demon companion, or even just the companion itself.

**Comment by Tyloris** [comment]
Current model for the warlock does not include invocations. It seems to be somewhat well-received, so it is unlikely that we will bring invocations back in.
