### ISSUE TITLE
Spell: Demon Skin is too powerful

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#378]
Using Warlock's Demon Skin spell they are able to massively boost a creatures AC for its duration. This leads to opening for massive abuse when multiclassing or when used on a creature with the _unarmored defense_ feature.
- This spell should probably only be usable on the caster (the warlock), rather than being able to be cast on another creature.
- This spell should count as a separate mean of calculating armor, as described on page 14 of the PHB.

**Comment by Tyloris** [comment]
Demon Skin was changed in the newest version of the warlock.
