### ISSUE TITLE
Warlock: Haunt Feature

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#391]
Haunt is a more fitting name for what Seed of Corruption actually does and could do with a renaming.

**Comment by orjanbp** [comment]
Managed to somehow forget that this was something we were considering. 🤔 Maybe we could actually work with this in the 3.0 rework of the Warlock, since we want Affliction to Haunt but have been a bit up in how to do it. Just using Seed of Corruption from 2.1 as a base would make a lot of sense.

**Comment by orjanbp** [comment]
Changing this issue to be a more general thread for Haunt as a feature for Affliction.
