### ISSUE TITLE
Druid: The survivability of shapeshifts

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#430]
We need to take another look at the "tankiness" of shapeshifts so that a moonkin with Celestial Defense isn't more tanky than the base-line bear form.

**Comment by Chokka99** [comment]
I believe that a partial solution to this problem would be making the Bear Form AC 12+CON.

This reflects the bear form fantasy of absorbing hits with a bristling hide and thick layers of fat, as opposed to avoiding the damage outright. (More of "the axe connects, but cannot penetrate deep enough to deal meaningful damage" and less of "you narrowly swing under the axe, the blade carving through the air above your head.")

This also has design precedent from Wizards of the Coast in the Loxodon's Natural Armor.

As an added bonus, this makes the Druid less MAD if they plan on prioritizing the Guardian playstyle, needing STR, CON, and some WIS vs needing STR, CON, DEX, and WIS.
