### ISSUE TITLE
Satyr: Should we change their creature type to Fiend?

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#496]
Should we change Satyrs creature type to fiends to better reflect the game?

**Comment by Tseims** [comment]
Definitely. Xavius was turned into a satyr by Sargeras himself and the curse that spread from him is described as demonic. It is possible that other demonic races have been corrupted in the same way. There is the question of whether satyrs return to the Twisting Nether upon death, but they share many physical features with other demons (horns, hooves, fangs, claws)
