### ISSUE TITLE
Nagas: Should their alignment be changed to something other than Unaligned?

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#504]
Nagas have been pitched as being _unaligned_, is this a good alignment for them? Most would say that Nagas are inherently evil creatures and the old 3.5 manuals do pitch them as being _neutral evil_ beings?
Would that be a better fit than Unaligned?

**Comment by Tseims** [comment]
Unaligned makes them feel more beastly than they are. Neutral Evil would be a better choice, as they usually work with other races for their own benefits rather than to oppose a mutual baddie

**Comment by orjanbp** [comment]
Neutral Evil sounds like a good pick, without overtly prescribing malice (Chaotic Evil) or implying they routinely rely on a higher power (Lawful Evil).
