### ISSUE TITLE
Feat: Firearm Adept giving wrong proficiency

### ISSUE THREAD

**Issue by Tseims** [Jihia/Warcraft-5e-Conversion#550]
The feat Firearm Adept currently gives proficiency in tinker's tools. Rogue rework changed manufacturing and customizing firearms to work with gunsmith's tools, so the feat should be changed accordingly

**Comment by orjanbp** [comment]
Should the Rogue rework come with errata for this part maybe? Changing this in the core book would be a HHB 3.0 issue. @Jihia
