### ISSUE TITLE
Unholy Death Knights and disease resistance/immunity

### ISSUE THREAD

**Issue by Silverblade1234** [Jihia/Warcraft-5e-Conversion#565]
Unholy DK: Do we want to add bypassing disease resistance/immunity? (This is only a thing in very specific PC features; monk, paladin, and now DK, as best I can tell. I'm fine with it being a niche weakness of Unholy.)

(Prompted by feedback from Tyloris.)

**Comment by Jihia** [comment]
Subclasses should have weaknesses, the class might be in the Heroes Handbook but even heroes will have trouble with some foes. Issue is closed.
