### ISSUE TITLE
Death Knight spell "death and decay" fluff

### ISSUE THREAD

**Issue by Silverblade1234** [Jihia/Warcraft-5e-Conversion#567]
Death and Decay: Add fluff about rotting vegetation and blighted ground and stuff (I don't care, but it might be a nice gesture towards Tyloris in acknowledgment of his feedback and what we used from him.)

(Prompted by feedback from Tyloris.)

**Comment by Jihia** [comment]
Tweaked the fluff. Issue is closed.
