### ISSUE TITLE
Death Knight and undead steeds

### ISSUE THREAD

**Issue by Silverblade1234** [Jihia/Warcraft-5e-Conversion#569]
Find Steed/Greater Steed: Can we add a note to the spell list that says the summoned steed is of type undead? No other changes needed. This is not generally done, but seems like a simple and okay special exception. It's not major enough to be a feature, but is nice flavor and does take care of an iconic DK thing.

(Prompted by feedback from Tyloris.)

**Comment by Jihia** [comment]
I'm not sure where we'd add a note saying so without it being clunky. It also leaves the door open for other areas where a spell isn't quite fitting the fantasy. I'd rather that we leave 5e spells be as is and let the individual table choose to summon an undead creature type steed
