### ISSUE TITLE
Death Knight: Dark Transformation spell

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#571]
**Tyloris:**

> What about Dark Transformation? It could be Polymorph into a specific CR, but affecting a corpse or an undead under your control.

Do we have / can we have / do we want an ability that fits the Dark Transformation spell niche for Death Knight?

**Comment by Silverblade1234** [comment]
I don't think it makes sense to design a spell for (a) half a subclass (pet unholy), or (b) used only to buff other spells. Unholy Frenzy is already taking care of buffing your undead pals.

**Comment by Jihia** [comment]
Agreed, Dark Transformation feels redundant and its fantasy is covered by Unholy's Frenzy. Issue is closed.
