### ISSUE TITLE
Death Knight: Dominate Person spell

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#572]
**Tyloris:**

> Dominate Person didn't make the cut?

Do we have the room to offer a Dominate Person spell to the death knight? Is it something we want to do?

**Comment by AceAzzermeen** [comment]
I don't see why they should have it.

**Comment by orjanbp** [comment]
Copypasting in from discussion thread

> The DK has a low-level subtheme of being a warrior who can impose their will on others, between Dark Command, Control Undead, Unholy Frenzy, etc. They have a better control over undead, but it's there.

Dark Command is already there in the form of Compelled Duel, though the idea of them subjugating someone entirely isn't entirely out of form for them.

**Comment by Silverblade1234** [comment]
I'd say that fantasy is taken care of better by the Hold spells (which DKs currently have) than Dominate, personally. That seems much more like a shadow priest / warlock thing.

**Comment by Jihia** [comment]
Indeed, directly dominating and controlling someone feels much more in the area of Warlock and Spriest than Death Knights, who only need to keep their target still to get the kill.
