### ISSUE TITLE
Death Knight: Mind Freeze / Counterspell missing from spell list

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#573]
**Tyloris:**

>  Mind Freeze didn't make it from the 2.0 version? Not even as Counterspell?

Counterspell is a 3rd level spell, so it would be available semi-late for the death knight. Probably not an issue, though?

**Comment by Silverblade1234** [comment]
We did discuss this briefly, and I think we were fine either way.

**Comment by orjanbp** [comment]
I'd say there's no reason for it not to be added, but we'd have to consider just how widely available we'd want counterspelling to be. 

In 5E, Counterspell is available for the Sorcerer, Warlock, and Wizard. In WoW, by obvious design, practically everyone has some form of spell interrupt available. Doubt we'd want to go that far with it here, but we should likely take a tally up on how many classes have it and how many classes we'd like to have it. 

A lot of people like to rap on Counterspell being a really powerful move to have, though it isn't really particularly out of balance. If the Death Knight had it, it'd be available from 9th level onward, out of way fewer spell slots overall.

**Comment by AceAzzermeen** [comment]
If at all maybe as a disadvantage on an concentrartion save

**Comment by Jihia** [comment]
We made an active decision to remove Mind Freeze and not add Counterspell as a replacement so that the ability to _interrupt_ an enemy spellcaster was not widely available to all classes.

**Comment by Tyloris** [comment]
Not necessary, I retract my objection.
