### ISSUE TITLE
Death Knight: Offering a Rune Tap ability

### ISSUE THREAD

**Issue by orjanbp** [Jihia/Warcraft-5e-Conversion#575]
There's no Rune Tap in the 3.0 death knight playtest. Do we want to make one available?

**Tyloris:**

> Rune Tap: Cure Wounds, self only. d10 die to compensate (same as your HD)

**Comment by Silverblade1234** [comment]
Death Coil serves this function.

**Comment by orjanbp** [comment]
You're right. And what Rune Tap should be doing if it was an option, is reduce damage taken rather than restore hit points. 

https://www.wowhead.com/spell=194679/rune-tap

**Comment by Jihia** [comment]
Death Coil does not allow the Death Knight to use it on themselves, but that is something we can change.
