### ISSUE TITLE
Death Knight: Rework Summon Undead?

### ISSUE THREAD

**Issue by AceAzzermeen** [Jihia/Warcraft-5e-Conversion#576]
The summon undead spell could be replaced by the new summon spells from unearthed arcana.
Just change the availible summons.
https://media.wizards.com/2020/dnd/downloads/UA2020-SpellsTattoos.pdf

Could also work for dark transformation.

**Comment by Silverblade1234** [comment]
I don't think this is needed. We already have a generic undead minion in the ghoul. I'd rather have a good selection of actual, specific undead monsters, that you can summon.

**Comment by Jihia** [comment]
I agree with what Silverblade has mentioned above. Death Knights should be capable of raising undead to their side, but directly summon spirits seems too far fetched for them.
