### ISSUE TITLE
Death Knight: Obliterate

### ISSUE THREAD

**Issue by Silverblade1234** [Jihia/Warcraft-5e-Conversion#578]
Tyloris: "There's a distinct lack of Obliterate. It's one of the core mechanics for Death Knights, and one of their iconic abilities. I know it wouldn't fit into the Frost DK class abilities, but what about as a spell?"

Silverblade: Obliterate is certainly core to Frost, but it's also just a boring damage button, with no extra function or anything. That's already occupied by Frost Strike. Giving it more weapon damage boosts is a bad idea, since we're staying away from that generally to maintain a DK - paladin contrast, and let paladin keep its shtick of massive burst. Moreover, Obliterate is already handled pretty well by Staggering Smite, so that any implementation would probably be too similar to that ability. I don't think it's appropriate to include.

**Comment by orjanbp** [comment]
Depending on the feature budget, we could maybe be able to lean into 

> A bonus action that allows you, the next time before the end of turn that you take an Attack action, to make two additional attacks. Basically Flurry of Blows.

Though then we'd most likely be looking at a long rest / short rest feature to let the death knight have one turn of two attacks.

Or if we decide at some point we're perfectly find entirely supplanting core 5E spells, replacing Staggering Smite with an Obliterate would fit the same bill. The root issue here is just that it's not there, when the reader expects it to be there.

**Comment by Silverblade1234** [comment]
For the former, that's basically already what Icy Talons does. That sort of effect feels more haste-y to me than Obliterate, which I associate with just a big bucket of damage.

I'd be okay with making it a 4th/5th level spell like Staggering Smite (4th), or a version of Banishing Smite that stuns rather than banishes (5th). I'm not sure it's totally necessary, but that implementation seems the best.

**Comment by Tyloris** [comment]
Not necessary, though I may touch on it in my revised version.
