### ISSUE TITLE
Death Knight spells

### ISSUE THREAD

**Issue by Silverblade1234** [Jihia/Warcraft-5e-Conversion#581]
Tyloris: "- Other missing abilities/spells: Death Gate (teleportation circle or transport via plants but with gravestones), On a Pale Horse (subability to turn your find steed undead), "

Silverblade: I like Find (Greater) Steed summoning undead, and made another ticket about it. Death Gate is iconic, but in the context of 5E, this is probably above the power level of DK spellcasting.  Some things that are trivial in WoW for the sake of convenience or balance are actually extremely powerful in 5E, and instant distant transportation certainly fits the bill. Also, it's not like we have an expectation of Acherus as a home base for DKs to travel to.

**Comment by AceAzzermeen** [comment]
Death Gate isn't needed. It only exists for gamplay reasons anyway.

**Comment by Jihia** [comment]
Agreed, i'd also add that Death Gate is a gameplay feature, not a fantasy one. issue is closed.
