### ISSUE TITLE
Death Knight Rune Strike name

### ISSUE THREAD

**Issue by Silverblade1234** [Jihia/Warcraft-5e-Conversion#582]
Tyloris: "Rune Strike: I didn't have a problem with the mechanic. I just noticed that you borrowed from my homebrew and I was suggesting a name that would fit better: Death Strike to go along with Death Coil."

Silverblade: Death Strike needs to have a healing component or it's not death strike, IMO! I'd sooner drop the necrotic damage than change the name from rune strike. See the related ticket for that.

**Comment by AceAzzermeen** [comment]
If a rename is under consideration i suggest scourge strike
