### ISSUE TITLE
Death Knight Summon Undead

### ISSUE THREAD

**Issue by Silverblade1234** [Jihia/Warcraft-5e-Conversion#583]
Tyloris: "Summon Gargoyle: Actually, looking at the equivalent spells, the Summon Undead spell probably needs to be reworked. Conjure Elemental is a 5th-level spell that can summon CR 5 or less, while Summon Undead is a 4th level spell that can summon the same CR level. The equivalent 4th level spell is Conjure Minor Elementals, which can summon a CR 2 or several lower CR monsters. So I'd probably either nerf the CR level that Summon Undead can summon (and can summon multiple), or boost its spell level. As for the gargoyle situation, you've already got a helpful section called Scourge in the Manual of Monsters that you can point to for options to summon."

Silverblade: Not relevant. Our spell is a direct port of Summon Greater Demon, and matches up with its CR, limitations, etc.

**Comment by Jihia** [comment]
Silverblade's comment is noted. Issue is closed.
