### ISSUE TITLE
Druid: Clarify Feral Tactics. 

### ISSUE THREAD

**Issue by Frogvall** [Jihia/Warcraft-5e-Conversion#621]
From Emmia:
In the 3.0 Druid's Feral Tactics feature, it is unclear when you can choose between Pack Defender and Pulverizing Mauler. 
• If the feature is intended to be chosen on levelup, it should say something like, "Choose one of the following features. You can use this feature when shapeshifted".
• If the feature is intended to be chosen on shapeshift, it should say something like, "When you use your Shapeshift, choose one of the following features, which you can use until you leave your shapeshifted form."

I don't actually like either of the ways I wrote that, from a writing standpoint. It could use some work.

**Comment by Jihia** [comment]
Clarified, closing the issue.
