### ISSUE TITLE
Kodo: Making kodos superior pack animals to horses

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#630]
Currently Kodos are weaker pack animals than most horses because of their lower Strength score (17 vs draft/war horses 18).
It has been suggested to add Mule's _Beast of Burden_ trait to Kodos to make them stronger pack animals.

**Comment by Tyloris** [comment]
After testing the kodos in the calculator, I found that the Strength of the non-ancient kodo can be increased up to 21 without changing its CR. Having a Strength of 21 plus the Beast of Burden ability would increase its carrying capacity to 1,260 lb., which is 60 lb. shy of the elephant's 1,320 lb. capacity.

**Comment by Tyloris** [comment]
Strength has been increased for both Kodo and Ancient Kodos, along with giving them the Beasts of Burden ability.
