### ISSUE TITLE
Elementals: Rebalancing

### ISSUE THREAD

**Issue by Jihia** [Jihia/Warcraft-5e-Conversion#631]
Rebalancing calculations run by Tyloris for elementals.

**_Tar Creeper._** Unchanged. (CR 8)
**_Core Hound._** Unchanged. (CR 7) Assumed that the armor and weapon destroying traits do not affect CR.
**_Dark Iron Hound._** Unchanged. (CR 2)
**_Dust Devil._** Clarification is needed on the range of gust. Unchanged. (CR 2)
**_Elemental, Air._** Was CR 6. Reduce damage of whirlwind to 2d8+2 to bring to CR 5.
**_Elemental, Arcane._** Was CR 4. Suggested add the following trait: "Magic Absorption: The elemental has advantage on saves against spells and other magical effects. If it successfully makes its save, it regains hit points equal to twice the spell's level." Increase number of hit dice to 10 (10d10 + 30 = 85 hp), and increasing Arcane Blast to deal 20 (8d4) damage instead. This results in a OCR, DCR, and CR of 5.
**_Elemental, Earth._** Was CR 7. Reduce the number of hit dice to 10 (10d10 + 50 = 105 hp), the AC to 16, and the damage dealt with slam to 1d12 + 5. Results in CR 5.
**_Elemental, Fire_**. Unchanged. (CR 5)
**_Elemental, Ice._** Unchanged. (CR 5)
**_Elemental, Water._** Was CR 6, under the assumption that Whelm counts as constrict, otherwise it is CR 5. Reduce hit dice to 11 (11d10 + 44 = 104 hp) to drop to CR 5.

Using the altered stats for the elementals, the revenants were calculated as:
**_Elemental Revenant, Air._** Was CR 6. 
**_Elemental Revenant, Arcane._** Was CR 6. 
**_Elemental Revenant, Earth._** Was CR 6.
**_Elemental Revenant, Fire._** Was CR 6. Assumed that weapon attacks do not set target aflame and that it cannot enter another's space. Either of these push its CR to 7.
**_Elemental Revenant, Ice._** Was CR 6.
**_Elemental Revenant, Water._** Was CR 6.
Suggest not changing this, and changing all revenants to be CR 6. The specific language of the sidebar needs rework, as there are some unclear points. 

**_Arcane Wyrm._** Damage was wrong for constrict, should be 8. Unchanged. (CR 2)
**_Mana Wyrm._** Unchanged. (CR 1/4)
**_Shale Spider._** Inconsistent attacks. One uses strength and the other dexterity. Counts as CR 3 if it uses Strength, CR 2 if it uses dexterity.
**_Lava Spider._** Was CR 2. Increasing its DPR to 21 *barely* pushes it into CR 3. I suggest increasing the d6s of the fire attacks to d8s.

**Comment by Tyloris** [comment]
The above values were determined using the calculator Jih linked. Since there have been issues with that calculator when working with lower CRs, some might need to be revisited to double check that they are accurate.
