### ISSUE TITLE
Mage: Spells

### ISSUE THREAD

**Issue by AceAzzermeen** [Jihia/Warcraft-5e-Conversion#646]
* Change range of Frostfire Bolt to 60, 90 or 120.

* Does Arcane Barrage need a str/athletics save like Bigby's Hand.
`Make a check with the hand's Strength contested by the Strength (Athletics) check of the target. If the target is Medium or smaller, you have advantage on the check. If you succeed, the hand pushes the target up to 5 feet plus a number of feet equal to five times your spellcasting ability modifier.`

* What is the point of *Flurry*? Is it essentially like Eldritch Blast, but with less range and damage, intended just to synergize with a frost mage's features?

**Comment by orjanbp** [comment]
Updated issue to add Flurry.

**Comment by AceAzzermeen** [comment]
addressed in rework
